### ISSUE TITLE
ReSummarization Tab Error

### ISSUE THREAD

**Issue by Csavoldi** [rmusser01/tldw#256]
**Are You on the Latest version?**
You did a git pull and are running the latest version/build?
Y/ Docker version CPU only

**Please describe the bug**
When running resummarization on content, I encounter an error within the Results:
"Error during database update: Error updating content: Error creating document version: database is locked"

**Is the bug reproducible reliably?**
Yes

**Steps to to reproduce the issue**
1. Go to 'Re-summarize tab search for an item'
2. Click on 'Re-Summarize'
3. See error after contect processes

**What was the expected behavior?**
Content to be summarized

**Screenshots**
If applicable, please add screenshots to help explain your problem.
![Screenshot from 2024-09-14 14-00-47](https://github.com/user-attachments/assets/37c59cf9-e58a-45a6-85e4-b2f3977ac400)

**Desktop (please complete the following information):**
 - OS: Fedora 40
 - Browser :Firefox
 - Date you performed the last git pull: Sept 144

**Any Additional context**
Please add any other context about the problem here. Thank you!

**Comment by rmusser01** [comment]
Solved.
