### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by IvanIVGrozny** [rmusser01/tldw#316]
**Are You on the Latest version?**
You did a git pull and are running the latest version/build?
Yes!

**Please describe the bug**
Upon double-clicking Windows_Run_tldw.bat, an error message appears:

`Database path: Databases/media_summary.db
Backup directory: C:\Users\Prodi\tldw\./tldw_DB_Backups/
ERROR:root:DocumentVersions table does not exist
Database path: C:\Users\Prodi\tldw\Databases\media_summary.db
Database path: C:\Users\Prodi\tldw\Databases\media_summary.db
Traceback (most recent call last):
  File "C:\Users\Prodi\tldw\summarize.py", line 18, in <module>
    from App_Function_Libraries.Gradio_Related import launch_ui
  File "C:\Users\Prodi\tldw\App_Function_Libraries\Gradio_Related.py", line 36, in <module>
    from App_Function_Libraries.Gradio_UI.MMLU_Pro_tab import create_mmlu_pro_tab
  File "C:\Users\Prodi\tldw\App_Function_Libraries\Gradio_UI\MMLU_Pro_tab.py", line 14, in <module>
    from App_Function_Libraries.Benchmarks_Evaluations.MMLU_Pro.MMLU_Pro_rewritten import (
  File "C:\Users\Prodi\tldw\App_Function_Libraries\Benchmarks_Evaluations\MMLU_Pro\MMLU_Pro_rewritten.py", line 14, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'`

This message is repeated after pasting a module into venv directory, only with another module. This seems endless, please help.

**Is the bug reproducable reliably?**
No idea

**Steps to to reproduce the issue**
Double click on Windows_Run_tldw.bat

**What was the expected behavior?**
A working program

**Screenshots**
![image](https://github.com/user-attachments/assets/6fe56b29-ceb2-4106-91ff-6e35f21aa517)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Opera
 - Date you performed the last git pull: 03.10.2023

**Comment by rmusser01** [comment]
Thank you for filing the issue, my understanding is that it is caused by the lack of the 'datasets' module in your local python installation. 
As the MMLU_Pro test is a WIP, I've commented it out, so that it should no longer be called currently, and will modify that when it is fully implemented. After doing so, I will update the `requirements.txt` to reflect the change.
