### ISSUE TITLE
ffmpeg is not installed via installer script

### ISSUE THREAD

**Issue by Csavoldi** [rmusser01/tldw#363]
**Are You on the Latest version?**
You did a git pull and are running the latest version/build?
Y

**Please describe the bug**
Installer script (Windows_Install_Update.bat) does not install ffmpeg resulting in transcribe/ summarize errors. 

**Is the bug reproducable reliably?**
Yes

**Steps to to reproduce the issue**

**What was the expected behavior?**
A clear and concise description of what you expected to happen, if there was no bug.

**Screenshots**
![image](https://github.com/user-attachments/assets/44134aaa-4eea-4878-ade0-623c46255da0)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Date you performed the last git pull: Today

**Any Additional context**
Please add any other context about the problem here. Thank you!

**Comment by rmusser01** [comment]
Thanks for filing the issue, I've resolved this in the latest update. 
Problem was that ffmpeg was downloaded but not placed into the 'Bin' folder.
