### ISSUE TITLE
Incorrect PDF parser referenced

### ISSUE THREAD

**Issue by vagenas** [rmusser01/tldw#423]
The PDF parser mentioned in this line is not the one actually used:
https://github.com/rmusser01/tldw/blob/d35170aae2634fab53856739107d525a2e87340f/App_Function_Libraries/Gradio_UI/PDF_ingestion_tab.py#L332

**Comment by rmusser01** [comment]
Thank you for the heads up, I've gone ahead and fixed that. Very cool project btw!
