### ISSUE TITLE
Unable to transcribe

### ISSUE THREAD

**Issue by adrian52999** [rmusser01/tldw#436]
**Are You on the Latest version?**
You did a git pull and are running the latest version/build?
Yes

**Please describe the bug**
I am trying to transcribe audio to text but I can not get it to work. No matter what I do, it always crashes. I've tried with multiple files and what ends up happening is that I have bunch of directories in the temp folder with the audio files, and the script keeps crashing after attempting to initialize whisper.

**Is the bug reproducable reliably?**
Yes, at least on my end.

**Steps to to reproduce the issue**
I cannot get transcription to work at all.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Date you performed the last git pull: I reinstalled it today.

**Any Additional context**
I managed to screenshot the cmd window the last millisecond before it autoclosed and saw this error:

INFO:root:speech-to-text: Starting transcription... 
INFO:root:Initializing new WhisperModel with size medium on device cuda 
INFO:faster whisper:Processing audio with duration 12:22.203 
Could not locate cudnn_ops64_9.d11. Please make sure it is in your library path! Invalid handle. 
Cannot load symbol cudnnCreateTensorDescriptor 

I have installed cudnn and CUDA drivers from NVIDIA's website, but the script keeps crashing. I tried updating it with no GPU support, and it still crashes. 
I tried using whisperXXL as stated in the readme, and then it cannot even start, throwing this error:

Default API Endpoint: openai 
Traceback (most recent call last):
File "D:\tldw\summarize.py", line 16, in <module> 
from App_Function_Libraries. Books. Book_Ingestion_Lib import ingest_folder, ingest text_file 
File "D:\tldw\App_Function_Libraries\Books\Book_Ingestion_Lib.py", line 31, in <module> 
from App_Function_Libraries.DB.DB Manager import add_media_with_keywords, add_media to_database 
File "D:\tldw\App_Function_Libraries\DB\DB_Manager.py", line 15, in <module> 
from App_Function_Libraries.DB.SQLite_DB import DatabaseError 
File "D:\tldw\App_Function_Libraries\DB\SQLite_DB.py", line 69, in <module> 
from App_Function_Libraries.Chunk_Lib import chunk_options, chunk_text 
File "D:\tldw\App_Function_Libraries\Chunk_Lib.py", line 20, in <module> 
from transformers import GPT2Tokenizer File "D:\tldw\venv\Lib\site-packages\transformers\ init .py", line 26, in <module> 
from . import dependency_versions_check 
File "D:\tldw\venv\Lib\site-packages\transformers\dependency_versions_check.py", line 16, in <module> 
from .utils.versions import require_version, require_version_core File "D:\tldw\venv\Lib\site-packages\transformers\utils\__init .py", line 27, in <module> 
from . chat_template_utils import DocstringParsingException, TypeHintParsingException, get_json_schema 
File "D:\tldw\venv\Lib\site-packages\transformers\utils\chat_template_utils.py", line 39, in <module> 
from torch import Tensor File "D:\tldw\venv\Lib\site-packages\torch\__init .py", line 130, in <module> 
raise err 
05Error: [WinError 127] The specified procedure could not be found. Error loading "D:\tldw\venv\Lib\site-packag es\torch\lib\cudnn_cnn_train64_8.d11" or one of its dependencies. 

I installed with the curl -0 method and tried using medium, medium.en and small whisper models. None work. 
Please help, I've been trying to get it to work for many hours and I still can't.

**Comment by rmusser01** [comment]
Thanks for filling this, sorry you’re having issues.

problem is that your python env isn’t seeing the CUDA installation.
There are two possible fixes, one is to change your system ENV path to include your cuda installation, and the other is to drop the two cuda DLL files into the tldw directory.

**Comment by adrian52999** [comment]
Hi, thank you for the response. I managed to get it to transcribe by placing the dll file in the tl/dw directory with the other dll files, and adding the CUDA directory to PATH (no idea why it wasn't done upon installation?) So now it's fixed. 

On another note, I was hoping to be able to transcribe multiple audio files at once, and I am a bit disappointed in being able to do it only one by one. I have around 2000 files I wanted to transcribe, and it looks like it's going to be impossible to do. Hopefully it is not too hard to add multi file processing?

Thank you.

**Comment by rmusser01** [comment]
Glad to hear its resolved, yea, idk either, fun stuff.

Yea, I've gone ahead and added that functionality. Was on my todo list anyways.
