### ISSUE TITLE
Improvement: Support AMD Cards on Windows

### ISSUE THREAD

**Issue by rmusser01** [rmusser01/tldw#59]
As a user, I would like to be able to use the application with an AMD GPU.

**Comment by Csavoldi** [comment]
I was able to get AMD card working by performing the following steps:
Goto:
https://learn.microsoft.com/en-us/windows/ai/directml/pytorch-windows

"
pip install torch-directml
"

replace requirments.txt file with the following:

[requirements.txt](https://github.com/rmusser01/tldw/files/15440980/requirements.txt)

**Comment by rmusser01** [comment]
Thank you, confirmed it works.
