### ISSUE TITLE
Enhancement: Add support for OpenRouter API

### ISSUE THREAD

**Issue by rmusser01** [rmusser01/tldw#66]
As a user, I would like to be able to use the OpenRouter API for making LLM requests.

As a user, when selecting the API endpoint from the drop down box, I should be able to select 'OpenRouter' as an option, and be able to use my API key and model selection as defined in the input box for the API key, and the model defined in `config.txt`, to have my requests for summarization handled by an LLM through the OpenRouter API.

**Comment by rmusser01** [comment]
Support added in GUI and non-gui.

**Comment by TomLucidor** [comment]
@rmusser01 from a pure UX perspective, when I select OpenRouter, it ought to give an extra bar on selecting models, otherwise it might not work... However about setting up config.txt, it might be best to add more documentation regarding model-setting (assuming things like Docker builds).
